In [81]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.2'

In [6]:
url="https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv"

In [7]:
df= pd.read_csv(url)

In [9]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [10]:
df.tail()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467

In [12]:
df.sample()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
3818                  280            NaN       157.0      3562.97408   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
3818           NaN        2005    USA    Diesel  Front-wheel drive        2.0   

      fuel_efficiency_mpg  
3818            12.173008

In [13]:
num_records= df.shape[0]

In [14]:
print(num_records)

9704


In [15]:
num_features= df.shape[1]

In [16]:
print(num_features)

11


In [21]:
df.shape

(9704, 11)

In [23]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [24]:
df['fuel_type'].nunique()

2

In [25]:
num_fuel_types= df['fuel_type'].nunique()

In [26]:
print(num_fuel_types)

2


In [27]:
df.isna()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   False          False       False           False   
1                   False          False       False           False   
2                   False           True       False           False   
3                   False          False        True           False   
4                   False          False       False           False   
...                   ...            ...         ...             ...   
9699                False          False       False           False   
9700                False           True       False           False   
9701                False          False       False           False   
9702                False          False       False           False   
9703                False          False       False           False   

      acceleration  model_year  origin  fuel_type  drivetrain  num_doors  \
0            False       False   False      False       False      False   
1            False       False   False      False       False      False   
2            False       False   False      False       False      False   
3            False       False   False      False       False      False   
4            False       False   False      False       False      False   
...            ...         ...     ...        ...         ...        ...   
9699         False       False   False      False       False       True   
9700         False       False   False      False       False      False   
9701         False       False   False      False       False      False   
9702         False       False   False      False       False      False   
9703         False       False   False      False       False      False   

      fuel_efficiency_mpg  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
9699                False  
9700                False  
9701                False  
9702                False  
9703                False  

[9704 rows x 11 columns]

In [34]:
 df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [35]:
(missing_counts>0).sum()

np.int64(4)

In [39]:
  df_asia =df[df['origin']== 'Asia']

In [40]:
print(df_asia)

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [43]:
max_efficiency_asia= df_asia['fuel_efficiency_mpg'].max()

In [44]:
print(max_efficiency_asia)

23.759122836520497


In [45]:
median_before= df['horsepower'].median()# before filling missing values

In [46]:
print(median_before)

149.0


In [49]:
mode_hp= df['horsepower'].mode()[0]

In [50]:
print(mode_hp)

152.0


In [58]:
df['horsepower']=  df['horsepower'].fillna(mode_hp)# filling missing value with mode 

In [60]:
print(df['horsepower'])

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64


In [61]:
df['horsepower'].isna().sum()

np.int64(0)

In [62]:
median_after= df['horsepower'].median()

In [63]:
median_after

np.float64(152.0)

In [64]:
asias_car= df[df['origin']== 'Asia']

In [65]:
asias_car

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [66]:
asias_cars_small= asias_car[['vehicle_weight', 'model_year']]

In [67]:
asias_cars_small

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [69]:
asias_cars_7= asias_cars_small.head(7)

In [70]:
asias_cars_7

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [71]:
X= asias_cars_7.values #convert to numpy array

In [72]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [77]:
XTX= X.T @X # compute x^T X

In [78]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [82]:
XTX_inv= np.linalg.inv(XTX) #invert the matrix

In [83]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [84]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])#create target vector y

In [85]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [86]:
w= XTX_inv @ X.T@y #compute regression coefficients w

In [87]:
w

array([0.01386421, 0.5049067 ])

In [88]:
sum_w= w.sum()#sum of coefficients

In [89]:
sum_w

np.float64(0.5187709081074016)